# Generated by Django 4.1.3 on 2022-11-17 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("famous_persons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Человек", "verbose_name_plural": "Люди"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Роль", "verbose_name_plural": "Роли"},
        ),
        migrations.AddField(
            model_name="person",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
    ]
