# Generated by Django 4.1.3 on 2022-11-19 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famous_persons", "0002_alter_person_options_alter_role_options_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="famous_persons.role"
            ),
        ),
    ]
